services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  fastapi:
    build: ./fastapi_app
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: uploads
    depends_on:
      - minio

  spark:
      image: tabulario/spark-iceberg
      container_name: spark-iceberg
      ports:
        - "8888:8888"  # Jupyter
        - "4040:4040"  # Spark UI
      environment:
        - AWS_ACCESS_KEY_ID=minioadmin
        - AWS_SECRET_ACCESS_KEY=minioadmin
        - AWS_REGION=us-east-1
      volumes:
        - ./spark_app:/home/iceberg/app
      depends_on:
        - minio

volumes:
  minio_data: